---
title: "Ordenar Datos Tesis"
author: "Vanessa Velázquez Mojica"
date: "9/2/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(ggplot2)
library(plotly)
library(stringr)
library(plyr)
library(dplyr)
library(class) # KNN
library(ROCR)
library(caret) # ConfusionMatrix
library(knitr) 
library(tidyr) # para manipulacion de datos
library(R.oo)
library(prettydoc)
library(purrr)
library(rpart)
library(randomForest)
library(neuralnet)
library(lubridate)

```

## CONTAMINANTES

```{r}
# cont10 <- read.csv("/Users/Vanessa/Desktop/TESIS/Datos/Horarios/Contaminantes/Descompresos/contaminantes_2010.csv")
# cont11 <- read.csv("/Users/Vanessa/Desktop/TESIS/Datos/Horarios/Contaminantes/Descompresos/contaminantes_2011.csv")
# cont12 <- read.csv("/Users/Vanessa/Desktop/TESIS/Datos/Horarios/Contaminantes/Descompresos/contaminantes_2012.csv")
# cont13 <- read.csv("/Users/Vanessa/Desktop/TESIS/Datos/Horarios/Contaminantes/Descompresos/contaminantes_2013.csv")
# cont14 <- read.csv("/Users/Vanessa/Desktop/TESIS/Datos/Horarios/Contaminantes/Descompresos/contaminantes_2014.csv")
# cont15 <- read.csv("/Users/Vanessa/Desktop/TESIS/Datos/Horarios/Contaminantes/Descompresos/contaminantes_2015.csv")
# cont16 <- read.csv("/Users/Vanessa/Desktop/TESIS/Datos/Horarios/Contaminantes/Descompresos/contaminantes_2016.csv")
# cont17 <- read.csv("/Users/Vanessa/Desktop/TESIS/Datos/Horarios/Contaminantes/Descompresos/contaminantes_2017.csv")

# contam <- as.data.frame(rbind(cont10,cont11,cont12,cont13,cont14,cont15,cont16,cont17))
# saveRDS(contam, "/Users/Vanessa/Desktop/Datos/Horarios/Contaminantes/contaminante_con_etiquetas.rds")

contaminantes <- readRDS("/Users/Vanessa/Desktop/TESIS/DatosParaTrabajar/contaminante_con_etiquetas.rds")
contaminantes$date <- as.Date(contaminantes$date)


```

### INDICE CALIDAD DEL AIRE

```{r}
# ica10 <- read.csv("/Users/Vanessa/Desktop/Datos/Horarios/Indice_Calidad_Aire/DescompresosICA/indice_2010.csv")
# ica11 <- read.csv("/Users/Vanessa/Desktop/Datos/Horarios/Indice_Calidad_Aire/DescompresosICA/indice_2011.csv")
# ica12 <- read.csv("/Users/Vanessa/Desktop/Datos/Horarios/Indice_Calidad_Aire/DescompresosICA/indice_2012.csv")
# ica13 <- read.csv("/Users/Vanessa/Desktop/Datos/Horarios/Indice_Calidad_Aire/DescompresosICA/indice_2013.csv")
# ica14 <- read.csv("/Users/Vanessa/Desktop/Datos/Horarios/Indice_Calidad_Aire/DescompresosICA/indice_2014.csv")
# ica15 <- read.csv("/Users/Vanessa/Desktop/Datos/Horarios/Indice_Calidad_Aire/DescompresosICA/indice_2015.csv")
# ica16 <- read.csv("/Users/Vanessa/Desktop/Datos/Horarios/Indice_Calidad_Aire/DescompresosICA/indice_2016.csv")
# ica17 <- read.csv("/Users/Vanessa/Desktop/Datos/Horarios/Indice_Calidad_Aire/DescompresosICA/indice_2017.csv")
 
# ica_todos <- as.data.frame(rbind(ica10,ica11,ica12,ica13,ica14,ica15,ica16,ica17))
 
# saveRDS(ica_todos, "/Users/Vanessa/Desktop/TESIS/DatosParaTrabajar/indice_calidad_aire.rds")

indices <- readRDS("/Users/Vanessa/Desktop/TESIS/DatosParaTrabajar/indice_calidad_aire.rds")

hist(indices$Noroeste.Ozono)
hist(indices$Noreste.Ozono)
hist(indices$Centro.Ozono)
```



### PARTICULAS

#### PLOMO

```{r}
# plomo <- read.csv("/Users/Vanessa/Desktop/Datos/Partículas/Plomo/red_manual_plomo.csv")
# saveRDS(plomo, "/Users/Vanessa/Desktop/TESIS/DatosParaTrabajar/red_manual_plomo.rds")
plomo <- readRDS("/Users/Vanessa/Desktop/TESIS/DatosParaTrabajar/red_manual_plomo.rds")
```


#### PM10 y PM2.5

```{r}
# particulas_susp <- read.csv("/Users/Vanessa/Desktop/Datos/Partículas/PM10_PM2.5/red_manual_particulas_susp.csv")
# saveRDS(particulas_susp, "/Users/Vanessa/Desktop/TESIS/DatosParaTrabajar/red_manual_part_susp.rds")
part_susp <- readRDS("/Users/Vanessa/Desktop/TESIS/DatosParaTrabajar/red_manual_part_susp.rds")
```


### Depósito Húmedo

#### Concentración - Humedo

```{r}
# dep_hum_concen <- read.csv("/Users/Vanessa/Desktop/Datos/Deposito_Humedo/Concentración/concentracion.csv")
# saveRDS(dep_hum_concen, "/Users/Vanessa/Desktop/TESIS/DatosParaTrabajar/dep_hum_concentracion.rds")
dep_hum_concen <- readRDS("/Users/Vanessa/Desktop/TESIS/DatosParaTrabajar/dep_hum_concentracion.rds")
```

#### Deposito - Humedo

```{r}
# dep_hum_depo <- read.csv("/Users/Vanessa/Desktop/Datos/Deposito_Humedo/Deposito/deposito.csv")
# saveRDS(dep_hum_depo, "/Users/Vanessa/Desktop/TESIS/DatosParaTrabajar/dep_hum_deposito.rds")
dep_hum_depo <- readRDS("/Users/Vanessa/Desktop/TESIS/DatosParaTrabajar/dep_hum_deposito.rds")
```

```{r}
depositohum <- rbind(dep_hum_concen, dep_hum_depo)
```

### Depósito Local

#### Concentración - Local

```{r}
# dep_loc_concen <- read.csv("/Users/Vanessa/Desktop/Datos/Deposito_Local/Concentracion/concentracion_local.csv")
# saveRDS(dep_loc_concen, "/Users/Vanessa/Desktop/TESIS/DatosParaTrabajar/dep_loc_concentracion.rds")
dep_loc_concen <- readRDS("/Users/Vanessa/Desktop/TESIS/DatosParaTrabajar/dep_loc_concentracion.rds")
```

#### Depósito - Local

```{r}
dep_loc_depo <- read.csv("/Users/Vanessa/Desktop/Datos/Deposito_Local/Deposito/deposito_local.csv")
saveRDS(dep_loc_depo, "/Users/Vanessa/Desktop/TESIS/DatosParaTrabajar/dep_loc_deposito.rds")
dep_loc_depo <- readRDS("/Users/Vanessa/Desktop/TESIS/DatosParaTrabajar/dep_loc_deposito.rds")
```

```{r}
depositoloc <- rbind(dep_loc_concen, dep_loc_depo)
```


### Meteorología

```{r}
meteo10 <- read.csv("/Users/Vanessa/Desktop/Datos/Horarios/Metereologia/DescompresosMet/meteo_2010.csv")
meteo11 <- read.csv("/Users/Vanessa/Desktop/Datos/Horarios/Metereologia/DescompresosMet/meteo_2011.csv")
meteo12 <- read.csv("/Users/Vanessa/Desktop/Datos/Horarios/Metereologia/DescompresosMet/meteo_2012.csv")
meteo13 <- read.csv("/Users/Vanessa/Desktop/Datos/Horarios/Metereologia/DescompresosMet/meteo_2013.csv")
meteo14 <- read.csv("/Users/Vanessa/Desktop/Datos/Horarios/Metereologia/DescompresosMet/meteo_2014.csv")
meteo15 <- read.csv("/Users/Vanessa/Desktop/Datos/Horarios/Metereologia/DescompresosMet/meteo_2015.csv")
meteo16 <- read.csv("/Users/Vanessa/Desktop/Datos/Horarios/Metereologia/DescompresosMet/meteo_2016.csv")
meteo17 <- read.csv("/Users/Vanessa/Desktop/Datos/Horarios/Metereologia/DescompresosMet/meteo_2017.csv")

# meteo <- as.data.frame(rbind(meteo10, meteo11, meteo12, meteo13, meteo14, meteo15, meteo16, meteo17))
# saveRDS(meteo, "/Users/Vanessa/Desktop/TESIS/DatosParaTrabajar/metereologia.rds")
# meteo <- readRDS("/Users/Vanessa/Desktop/TESIS/DatosParaTrabajar/metereologia.rds")
```

### Presión Atmosférica

```{r}
pa10 <- read.csv("/Users/Vanessa/Desktop/Datos/Horarios/Presión_Atmosférica/PA_2010.csv")
pa11 <- read.csv("/Users/Vanessa/Desktop/Datos/Horarios/Presión_Atmosférica/PA_2011.csv")
pa12 <- read.csv("/Users/Vanessa/Desktop/Datos/Horarios/Presión_Atmosférica/PA_2012.csv")
pa13 <- read.csv("/Users/Vanessa/Desktop/Datos/Horarios/Presión_Atmosférica/PA_2013.csv")
pa14 <- read.csv("/Users/Vanessa/Desktop/Datos/Horarios/Presión_Atmosférica/PA_2014.csv")
pa15 <- read.csv("/Users/Vanessa/Desktop/Datos/Horarios/Presión_Atmosférica/PA_2015.csv")
pa16 <- read.csv("/Users/Vanessa/Desktop/Datos/Horarios/Presión_Atmosférica/PA_2016.csv")
pa17 <- read.csv("/Users/Vanessa/Desktop/Datos/Horarios/Presión_Atmosférica/PA_2017.csv")

# pa <- as.data.frame(merge(pa10,pa11,pa12,pa13,pa14,pa15,pa16,pa17, by = date)
# pa <- as.data.frame(cbind(pa10,pa11,pa12,pa13,pa14,pa15,pa16,pa17))
# saveRDS(pa, "/Users/Vanessa/Desktop/TESIS/DatosParaTrabajar/presion_atm.rds")

# pa <- readRDS("/Users/Vanessa/Desktop/TESIS/DatosParaTrabajar/presion_atm.rds")

```


### Radiación UV

#### UV-A
```{r}

uva10 <- read.csv("/Users/Vanessa/Desktop/Datos/Radiacion_UV/UV_A/UVA_2010.csv")
uva11 <- read.csv("/Users/Vanessa/Desktop/Datos/Radiacion_UV/UV_A/UVA_2011.csv")
uva12 <- read.csv("/Users/Vanessa/Desktop/Datos/Radiacion_UV/UV_A/UVA_2012.csv")
uva13 <- read.csv("/Users/Vanessa/Desktop/Datos/Radiacion_UV/UV_A/UVA_2013.csv")
uva14 <- read.csv("/Users/Vanessa/Desktop/Datos/Radiacion_UV/UV_A/UVA_2014.csv")
uva15 <- read.csv("/Users/Vanessa/Desktop/Datos/Radiacion_UV/UV_A/UVA_2015.csv")
uva16 <- read.csv("/Users/Vanessa/Desktop/Datos/Radiacion_UV/UV_A/UVA_2016.csv")
uva17 <- read.csv("/Users/Vanessa/Desktop/Datos/Radiacion_UV/UV_A/UVA_2017.csv")

# uv_a <- as.data.frame(cbind(uva10,uva11,uva12,uva13,uva14,uva15,uva16,uva17))
# saveRDS(uva_a, "/Users/Vanessa/Desktop/TESIS/DatosParaTrabajar/uv_a.rds")
# 
# uv_a <- readRDS("/Users/Vanessa/Desktop/TESIS/DatosParaTrabajar/uv_a.rds")
```

#### UV-B
```{r}
uvb10 <- read.csv("/Users/Vanessa/Desktop/Datos/Radiacion_UV/UV_B/UVB_2010.csv")
uvb11 <- read.csv("/Users/Vanessa/Desktop/Datos/Radiacion_UV/UV_B/UVB_2011.csv")
uvb12 <- read.csv("/Users/Vanessa/Desktop/Datos/Radiacion_UV/UV_B/UVB_2012.csv")
uvb13 <- read.csv("/Users/Vanessa/Desktop/Datos/Radiacion_UV/UV_B/UVB_2013.csv")
uvb14 <- read.csv("/Users/Vanessa/Desktop/Datos/Radiacion_UV/UV_B/UVB_2014.csv")
uvb15 <- read.csv("/Users/Vanessa/Desktop/Datos/Radiacion_UV/UV_B/UVB_2015.csv")
uvb16 <- read.csv("/Users/Vanessa/Desktop/Datos/Radiacion_UV/UV_B/UVB_2016.csv")
uvb17 <- read.csv("/Users/Vanessa/Desktop/Datos/Radiacion_UV/UV_B/UVB_2017.csv")

# uv_b <- as.data.frame(cbind(uvb10,uvb11,uvb12,uvb13,uvb14,uvb15,uvb16,uvb17))
# saveRDS(uva_b, "/Users/Vanessa/Desktop/TESIS/DatosParaTrabajar/uv_b.rds")
# 
# uv_b <- readRDS("/Users/Vanessa/Desktop/TESIS/DatosParaTrabajar/uv_b.rds")
```

### Promedios

### Dióxido de Azufre SO2
```{r}
prom_so2 <- read_csv("/Users/Vanessa/Desktop/Datos/Promedios 24 Hrs/prome_so2.csv")
saveRDS(prom_so2,"/Users/Vanessa/Desktop/TESIS/DatosParaTrabajar/prom_so2.rds")
prom_so2 <- readRDS("/Users/Vanessa/Desktop/TESIS/DatosParaTrabajar/prom_so2.rds")
prom_so2$Date<-as.Date(prom_so2$Date)
names(prom_so2) <- c("date", "id_station", "id_param_so2", "value_so2", "unit_so2")
head(prom_so2)
```

### Particulas Suspendidas PM10 y PM2.5

```{r}
prom_ps <- read_csv("/Users/Vanessa/Desktop/Datos/Promedios 24 Hrs/prom_ps.csv")
saveRDS(prom_ps, "/Users/Vanessa/Desktop/TESIS/DatosParaTrabajar/prom_ps.rds")
prom_ps <- readRDS("/Users/Vanessa/Desktop/TESIS/DatosParaTrabajar/prom_ps.rds")

 # prom_ps$Date<-as.Date(prom_ps$Date)
# names(prom_ps) <- c("date", "id_station", "id_param_ps", "value_ps", "unit_ps")
# head(prom_ps)
```


